### PR TITLE
Improved logging

### LINKED ISSUE #65: Need more comprehensive logging of activity
There should be a lot more logging by default in `update_mag_supplement.py`. I just started running it and it has been sitting at the last line for about 20 minutes:
```
ska3-kady$ python agasc/scripts/update_mag_supplement.py
Excluding bad stars
Skipping 80059 stars already in the supplement
Will process 2785 stars on 14399 observations
```

### LINKED ISSUE #75: Disabled warnings question
In `agasc/scripts/update_mag_supplement.py` there is code to disable all numpy warnings and all UserWarnings. 

What's the driver for these?

### PR DESCRIPTION
**Pull request by javierggt**
## Description

This PR addresses issue #65 and includes a few more logging messages. The specific request in #65 was addressed by adding a progress bar using tqdm.

To be applied after PR #76.

## Testing

- [x] Passes unit tests on MacOS, linux, Windows (at least one required)
- [x] Functional testing: updated supplement and generated reports

Fixes #65 
Closes #75

### CODE REVIEW

**Comment by javierggt** [comment]
I marked it as "ready for review". I can add more logging messages if people want...

**Comment by taldcroft** [comment]
Needs a rebase on the updated master.

**Comment by javierggt** [comment]
yes, rebase comes after the other PR is merged.

**Comment by taldcroft** [comment]
Use `from ska_helpers.run_info import log_run_info` to log the run information. (see `kadi/update_cmds.py` for an example).

**Comment by taldcroft** [comment]
The progress bar is great for the rare cases in the future of running this by hand, but the reality is that this will be a cron job. It should have verbose output of all the steps being taken for each star. See `/proj/sot/ska/data/eng_archive/logs/daily.0/eng_archive.log` for an example. This is not perfect since it is mostly the same thing on 7000 obsids.

Each notable processing step and results should be reflected in the logs, where this is this is especially so for a suspect star-obs. Typically when you are reading from a file or files, or writing to a file, provide information.

The upshot is that there is a lot going on in this complex processing. The steps along the way should all be logged, which will be a big help for the inevitable failures that will happen at some point. I would not be surprised to have 50 to 100 lines of output for a typical star, or 10-50k lines of logging per weekly run.

**Comment by javierggt** [comment]
ah, I didn't know you wanted that much logs. Will do.

**Comment by taldcroft** [comment]
This looks great! Comments:
- In one run it reported getting an exception during report generation. I'm not sure if that was just from things being corrupted since I aborted the script a few times in the middle. I'm not worried as long as things are working for you.
- The more important bit is that any exception message like that should include the word `ERROR` or `Error` in the text so that our post-run checking (watchcron) flags it.
- When running in the cron job you would want to have `--log-level=debug`. I feel like debug is not the right word here, because debug is not what is typically wanted during production running. This is pretty much why I invented the new `verbose` level in pyyaks, which fits in with this "verbose" level of logging. At the end though this is all just semantics and I don't really care as long as the production logging has all the current logging labeled as `debug`.
- I see that the progress bar actually works quite nicely along with logging and gives the very useful indicator of progress along the way. Since this works nicely and is so useful, I would propose making the default be to show the progress bar, with a `-no-progress-bar` option to disable it. I'm not sure in what situation we actually want to disable it. If it doesn't completely mess things up I'd even leave this in the production logging to file.
- A nit that you can address or not: in a few places the `mag` gets shown as a full float instead of to 3 digits. Cleaning up the formatting would be nice.

**Comment by taldcroft** [comment]
@javierggt - if you'd like to bump my comments out to new issues and merge this PR as-is, then that's fine by me. This can let us move on to the next PR (where you can rebase and I review).

**Comment by javierggt** [comment]
I made a commit with a few changes related to what you just suggested. I think I got all.

**Pull request merged**
